### PR TITLE
Add PRD

### PR DESCRIPTION
**Pull request by neruthes**
Or should we translate to English?

### CODE REVIEW

**Comment by yangsheng6810** [comment]
Should we just use plain text format, like Markdown or Org, since both can be rendered nicely on Github?

**Comment by neruthes** [comment]
Added Markdown format. Does it look good?

**Comment by yangsheng6810** [comment]
What do you think if we just remove the tex and pdf part, and keep only the Markdown? There is no point in maintaining several different copy of the same thing.

**Comment by neruthes** [comment]
It is ok to remove other versions. The Markdown version should be sufficient.

**Pull request merged**
